package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/danieldev/czech-go-system/backend/internal/contracts"
)

// ── Rate limiter ─────────────────────────────────────────────────────────────

const aiImageRateLimit = 5 // max requests per minute per admin

type rateWindow struct {
	count     int
	windowEnd time.Time
}

type aiImageRateLimiter struct {
	mu      sync.Mutex
	windows map[string]rateWindow
}

func newAiImageRateLimiter() *aiImageRateLimiter {
	return &aiImageRateLimiter{windows: make(map[string]rateWindow)}
}

// allow returns true if the admin may make another request this minute.
func (rl *aiImageRateLimiter) allow(email string) bool {
	rl.mu.Lock()
	defer rl.mu.Unlock()

	now := time.Now()
	w := rl.windows[email]
	if now.After(w.windowEnd) {
		// New or expired window — reset.
		rl.windows[email] = rateWindow{count: 1, windowEnd: now.Add(time.Minute)}
		return true
	}
	if w.count >= aiImageRateLimit {
		return false
	}
	w.count++
	rl.windows[email] = w
	return true
}

// replicateBaseURL is the base URL for Replicate API calls. Overrideable in tests.
var replicateBaseURL = "https://api.replicate.com"

// ── Handler ───────────────────────────────────────────────────────────────────

// handleAdminGenerateImage serves POST /v1/admin/ai/generate-image.
// Calls Replicate Flux.1-schnell, downloads the result, and saves it as a
// local asset, returning asset_id + preview_url (Replicate CDN URL).
func (s *Server) handleAdminGenerateImage(w http.ResponseWriter, r *http.Request, user contracts.User) {
	if r.Method != http.MethodPost {
		writeMethodNotAllowed(w)
		return
	}

	if s.replicateAPIKey == "" {
		writeError(w, http.StatusServiceUnavailable, "not_configured",
			"AI image generation not configured (REPLICATE_API_KEY not set).", false)
		return
	}

	var req struct {
		Prompt string `json:"prompt"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "validation_error", "Invalid JSON body.", false)
		return
	}
	prompt := strings.TrimSpace(req.Prompt)
	if len(prompt) < 3 {
		writeError(w, http.StatusBadRequest, "validation_error", "Prompt must be at least 3 characters.", false)
		return
	}
	if len(prompt) > 500 {
		writeError(w, http.StatusBadRequest, "validation_error", "Prompt must be at most 500 characters.", false)
		return
	}

	if !s.aiImageRL.allow(user.Email) {
		writeError(w, http.StatusTooManyRequests, "rate_limited",
			fmt.Sprintf("Rate limit: %d requests per minute exceeded. Try again shortly.", aiImageRateLimit), false)
		return
	}

	ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
	defer cancel()

	predictionID, err := createReplicatePrediction(ctx, s.replicateAPIKey, prompt)
	if err != nil {
		log.Printf("ai/generate-image: create prediction: %v", err)
		writeError(w, http.StatusServiceUnavailable, "replicate_error", "Failed to start image generation.", true)
		return
	}

	outputURL, err := pollReplicatePrediction(ctx, s.replicateAPIKey, predictionID)
	if err != nil {
		log.Printf("ai/generate-image: poll prediction %s: %v", predictionID, err)
		if ctx.Err() != nil {
			writeError(w, http.StatusGatewayTimeout, "generation_timeout", "Image generation timed out after 30s.", true)
			return
		}
		writeError(w, http.StatusServiceUnavailable, "replicate_error", "Image generation failed: "+err.Error(), true)
		return
	}

	imageBytes, err := downloadImage(ctx, outputURL)
	if err != nil {
		log.Printf("ai/generate-image: download %s: %v", outputURL, err)
		writeError(w, http.StatusServiceUnavailable, "download_error", "Failed to download generated image.", true)
		return
	}

	assetID := newLocalAssetID()
	storageKey := fmt.Sprintf("ai-generated/%s.jpg", assetID)
	filePath := localExerciseAssetPath(storageKey)

	if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
		writeError(w, http.StatusInternalServerError, "internal_error", "Could not prepare image storage.", true)
		return
	}
	if err := os.WriteFile(filePath, imageBytes, 0o644); err != nil {
		writeError(w, http.StatusInternalServerError, "internal_error", "Could not save generated image.", true)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"data": map[string]any{
			"asset_id":    assetID,
			"storage_key": storageKey,
			"preview_url": outputURL, // Replicate CDN URL — valid ~24h
		},
		"meta": map[string]any{},
	})
}

// handleAdminAiSetBanner serves POST /v1/admin/ai/set-banner.
// Promotes an AI-generated asset (storage_key) as the banner for a course or mock-test.
// The file must already exist (generated by handleAdminGenerateImage).
func (s *Server) handleAdminAiSetBanner(w http.ResponseWriter, r *http.Request, user contracts.User) {
	if r.Method != http.MethodPost {
		writeMethodNotAllowed(w)
		return
	}

	var req struct {
		EntityType string `json:"entity_type"` // "course" | "mock-test"
		EntityID   string `json:"entity_id"`
		StorageKey string `json:"storage_key"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "validation_error", "Invalid JSON body.", false)
		return
	}
	req.EntityType = strings.TrimSpace(req.EntityType)
	req.EntityID = strings.TrimSpace(req.EntityID)
	req.StorageKey = strings.TrimSpace(req.StorageKey)

	if req.EntityType == "" || req.EntityID == "" || req.StorageKey == "" {
		writeError(w, http.StatusBadRequest, "validation_error", "entity_type, entity_id, and storage_key are required.", false)
		return
	}
	// Security: only allow ai-generated storage keys.
	if !strings.HasPrefix(req.StorageKey, "ai-generated/") {
		writeError(w, http.StatusBadRequest, "validation_error", "storage_key must be an AI-generated asset.", false)
		return
	}

	// Verify file exists on disk.
	filePath := localExerciseAssetPath(req.StorageKey)
	if _, err := os.Stat(filePath); err != nil {
		writeError(w, http.StatusNotFound, "not_found", "AI-generated asset not found. Generate image first.", false)
		return
	}

	var ok bool
	switch req.EntityType {
	case "course":
		ok = s.repo.SetCourseBannerImage(req.EntityID, req.StorageKey)
	case "mock-test":
		ok = s.repo.SetMockTestBannerImage(req.EntityID, req.StorageKey)
	case "grammar-rule":
		ok = s.repo.SetGrammarRuleImage(req.EntityID, req.StorageKey)
	case "vocabulary-item":
		ok = s.repo.SetVocabularyItemImage(req.EntityID, req.StorageKey)
	default:
		writeError(w, http.StatusBadRequest, "validation_error", "entity_type must be 'course', 'mock-test', 'grammar-rule', or 'vocabulary-item'.", false)
		return
	}
	if !ok {
		writeNotFound(w)
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"data": map[string]any{
			"entity_id":   req.EntityID,
			"entity_type": req.EntityType,
			"storage_key": req.StorageKey,
		},
		"meta": map[string]any{},
	})
}

// ── Replicate client ──────────────────────────────────────────────────────────

const replicateFluxModel = "black-forest-labs/flux-schnell"


type replicatePredictionResponse struct {
	ID     string `json:"id"`
	Status string `json:"status"`
	Output []string `json:"output"`
	Error  string `json:"error"`
}

func createReplicatePrediction(ctx context.Context, apiKey, prompt string) (string, error) {
	body, _ := json.Marshal(map[string]any{
		"input": map[string]any{
			"prompt":        prompt,
			"num_outputs":   1,
			"output_format": "jpg",
		},
	})

	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		replicateBaseURL+"/v1/models/"+replicateFluxModel+"/predictions",
		bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Token "+apiKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("replicate HTTP %d: %s", resp.StatusCode, string(b))
	}

	var pr replicatePredictionResponse
	if err := json.NewDecoder(resp.Body).Decode(&pr); err != nil {
		return "", fmt.Errorf("decode prediction response: %w", err)
	}
	if pr.ID == "" {
		return "", fmt.Errorf("empty prediction ID in response")
	}
	return pr.ID, nil
}

func pollReplicatePrediction(ctx context.Context, apiKey, predictionID string) (string, error) {
	url := replicateBaseURL + "/v1/predictions/" + predictionID
	for {
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		default:
		}

		req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		if err != nil {
			return "", err
		}
		req.Header.Set("Authorization", "Token "+apiKey)

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return "", err
		}
		var pr replicatePredictionResponse
		err = json.NewDecoder(resp.Body).Decode(&pr)
		resp.Body.Close()
		if err != nil {
			return "", fmt.Errorf("decode poll response: %w", err)
		}

		switch pr.Status {
		case "succeeded":
			if len(pr.Output) == 0 {
				return "", fmt.Errorf("prediction succeeded but output is empty")
			}
			return pr.Output[0], nil
		case "failed", "canceled":
			msg := pr.Error
			if msg == "" {
				msg = pr.Status
			}
			return "", fmt.Errorf("prediction %s: %s", pr.Status, msg)
		}
		// still processing — wait before next poll
		select {
		case <-ctx.Done():
			return "", ctx.Err()
		case <-time.After(500 * time.Millisecond):
		}
	}
}

func downloadImage(ctx context.Context, url string) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("download HTTP %d", resp.StatusCode)
	}
	const maxBytes = 20 * 1024 * 1024 // 20 MB guard
	return io.ReadAll(io.LimitReader(resp.Body, maxBytes))
}
