-- V37 — per-item Polly TTS for vocab items.
--
-- Adds a single column that stores the Polly-synthesised MP3 storage key
-- generated by POST /v1/admin/vocabulary-items/:id/generate-audio. The
-- empty string ("") means "no audio yet" so the column is NOT NULL with a
-- safe default — matches the V20 image_asset_id pattern on the same
-- table, which lets existing CREATE statements continue to work without
-- listing the new column.

ALTER TABLE vocabulary_items
    ADD COLUMN IF NOT EXISTS audio_storage_key TEXT NOT NULL DEFAULT '';
